# Generated by Django 3.2.9 on 2021-11-11 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=14)),
                ('subscription', models.CharField(max_length=100)),
                ('subscription_start', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_end', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan_name', models.CharField(max_length=100)),
                ('subscription_plan_type', models.CharField(max_length=100)),
                ('subscription_plan_amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn_number', models.CharField(max_length=14, unique=True)),
                ('stripe_id', models.CharField(max_length=256)),
                ('subscription_id', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
                ('is_subscribe', models.BooleanField(default=True)),
                ('subscription_plan', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriber.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_number', models.CharField(max_length=14, unique=True)),
                ('stripe_id', models.CharField(max_length=256)),
                ('subscription_id', models.CharField(blank=True, max_length=256, null=True)),
                ('start_date', models.CharField(max_length=256)),
                ('end_date', models.CharField(max_length=256)),
                ('is_subscribe', models.BooleanField(default=True)),
                ('subscription_plan', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriber.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
