# Generated by Django 3.2.9 on 2021-11-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_plan',
            field=models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriptionplan'),
        ),
    ]
