# Generated by Django 3.2.9 on 2021-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isSubscribe',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
