# Generated by Django 3.2.9 on 2021-11-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
